#!/usr/bin/env python3
import os

p = "pip"
os.system(p + " install pyrebase")
os.system(p + " install PyQt5")
os.system(p + " install selenium")

print('Finished installing selenium, PyQt5 and pyrebase')
